### PR TITLE
Add UPC field to beverages

### PR DESCRIPTION
**Pull request by mascott**
I've added the UPC field along with a custom upc_length validation which
ensures the UPC code is one of the standard lengths (8 or 12
characters).

### CODE REVIEW

**Comment by amar47shah** [comment]
hey @mascott do you have a link that indicates that a UPC code should either be exactly 8 or exactly 12 characters? The [Wikipedia article](https://en.wikipedia.org/wiki/Universal_Product_Code) says that 12 is standard and mentions a 6-character variation.

I ask because it seems overly specific to resort to a custom validation method at this stage. Maybe we could just add the field and not validate its length?

**Comment by mascott** [comment]
I do not. I looked at the same Wikipedia article then walked around my local liquor store randomly sampling UPCs. Clearly an incredibly scientific method for determining the correct value. :smile: 

I mostly added the custom validation because I haven't had a use for one before and thought it'd be fun to figure out. I'm happy to leave that validation off for the time being if you think it might cause us pain.

**Comment by amar47shah** [comment]
Haha yes, I do think custom validation _presents an opportunity_ for pain, at least. I am dealing with complex and excessive custom validation at work right now, so it really jumps out at me.

I'd recommend either leaving out the length validation on this field or using a criterion supported by `validates_length_of`. It may turn out that we don't have a need for length validation after all, especially if someday the main form of data entry will be directly scanning the barcode.

I'm wondering if this is a good rule of thumb: "Don't validate assertions about data until your code _relies_ on those assertions."

**Comment by amar47shah** [comment]
PS: I like the use of shoulda-matchers with Minitest. I have always loved shoulda-matchers but only used them with RSpec. This is the first Rails app I've worked on that uses Minitest.

**Comment by amar47shah** [comment]
Force-pushing to rebase this branch over master.

**Comment by amar47shah** [comment]
Removed the length validation for upc and merging this. Time to move on :)

**Comment by mascott** [comment]
:+1:  Thanks, been distracted! 

This is the first time I've used Minitest too.

**Pull request merged**
